- name: 尝试推送离线dnscache镜像（若执行失败，可忽略）
  copy: src={{ base_dir }}/down/{{ dnscache_offline }} dest=/opt/kube/images/{{ dnscache_offline }}
  when: 'dnscache_offline in download_info.stdout'

- name: 获取dnscache离线镜像推送情况
  command: "ls /opt/kube/images"
  register: image_info

- name: 导入dnscache的离线镜像（若执行失败，可忽略）
  shell: "{{ bin_dir }}/docker load -i /opt/kube/images/{{ dnscache_offline }}"
  when: 'dnscache_offline in image_info.stdout and CONTAINER_RUNTIME == "docker"'

- name: 导入dnscache的离线镜像（若执行失败，可忽略）
  shell: "{{ bin_dir }}/ctr -n=k8s.io images import /opt/kube/images/{{ dnscache_offline }}"
  when: 'dnscache_offline in image_info.stdout and CONTAINER_RUNTIME == "containerd"'

- name: 准备dnscache的部署文件
  template: src=dns/nodelocaldns-ipvs.yaml.j2 dest={{ cluster_dir }}/yml/nodelocaldns.yaml
  when: "PROXY_MODE == 'ipvs'"
  run_once: true
  connection: local

- name: 准备dnscache的部署文件
  template: src=dns/nodelocaldns-iptables.yaml.j2 dest={{ cluster_dir }}/yml/nodelocaldns.yaml
  when: "PROXY_MODE == 'iptables'"
  run_once: true
  connection: local

- name: 创建dnscache部署
  shell: "{{ base_dir }}/bin/kubectl apply -f {{ cluster_dir }}/yml/nodelocaldns.yaml"
  run_once: true
  connection: local
